version: "3.4"

volumes:
  tmp:
  models:

services:
  app:
    image: boom-static-website
    build:
      context: ./demo
      args:
        API_BASE_URL: http:\/\/localhost:3000

    ports:
      - "8080:80"
  api:
    image: boom-api
    build: .
    environment:
      NODE_ENV: production
    env_file:
      - docker.env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  # see https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-docker-image
  worker_2stems:
    image: boom-worker
    build:
      context: ./worker
    env_file:
      - ./worker/docker.env
    volumes:
      - tmp:/app/tmp
      - models:/app/pretrained_models
    depends_on:
      - redis
    environment:
      - REDIS_QUEUE=queue:split:2stems

  # worker_4stems:
  #   image: boom-worker
  #   build:
  #     context: ./worker
  #   env_file:
  #     - ./worker/docker.env
  #   volumes:
  #     - tmp:/app/tmp
  #     - models:/app/pretrained_models
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_QUEUE=queue:split:4stems

  # worker_5stems:
  #   image: boom-worker
  #   build:
  #     context: ./worker
  #   env_file:
  #     - ./worker/docker.env
  #   volumes:
  #     - tmp:/app/tmp
  #     - models:/app/pretrained_models
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_QUEUE=queue:split:5stems


  # see https://github.com/docker-library/docs/blob/55604f7900451290144c0081e7f622297e519f61/redis/README.md#start-with-persistent-storage
  redis:
    image: redis
    ports:
      - "6379:6379"
