version: "3.4"

volumes:
  tmp:
  models:

services:
  app:
    image: boom-static-website
    build:
      context: ./demo
      args:
        API_BASE_URL: http:\/\/localhost:3000
        API_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpGeEhfYWQyYjlFZjFPeEJUWExDWCJ9.eyJpc3MiOiJodHRwczovL2Rldi1yZ2toM2U0MC5ldS5hdXRoMC5jb20vIiwic3ViIjoiUFp1WHFnVnVWN0ZWSDh3bEhVanhYcTByVzZMRkVxNG1AY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vcHJvdGVjdGVkLWRlcHRocy05MjA0Mi5oZXJva3VhcHAuY29tLyIsImlhdCI6MTU4OTc5Njg4NSwiZXhwIjoxNTg5ODgzMjg1LCJhenAiOiJQWnVYcWdWdVY3RlZIOHdsSFVqeFhxMHJXNkxGRXE0bSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.bgCn6-NUhOcZMNWZehDBsZi0hHrncX3_ZuRqymn9HvkrIsYQHQ-liewpse8zq3kDDCcf9n7jhrNG6niNBZ6I7CqO26Dlh183SUwP0j-1RvnVq3SjX3R8-fLkhPOXfcFSmEZ5k3_I_fPrivkzo47mtLtK8cmEFqx2r41n6ZFjrnGFpyBsF8JH7dM2MLFScyrFFWVERmJdh3E8bkPGcdOrHqPqKx68dX_1MMXpwPg2NqYfjymC2Ouw0bKrhRC8u6PEQJw4bx4uzkAru8gTHjkUHU7xpkGKelb4sulMgCiRkeHya6qAUYCOYbQ1BmSq0m-xx3L5dRxUB3s4X_vjypDb-w
    env_file:
      - ./demo/docker.env

    ports:
      - "8080:80"
  api:
    image: boom-api
    build:
      context: ./api
    environment:
      NODE_ENV: production
    env_file:
      - ./api/docker.env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  # see https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-docker-image
  worker_2stems:
    image: boom-worker
    build:
      context: ./worker
    env_file:
      - ./worker/docker.env
    volumes:
      - tmp:/app/tmp
      - models:/app/pretrained_models
    depends_on:
      - redis
    environment:
      - REDIS_QUEUE=queue:split:2stems

  # worker_4stems:
  #   image: boom-worker
  #   build:
  #     context: ./worker
  #   env_file:
  #     - ./worker/docker.env
  #   volumes:
  #     - tmp:/app/tmp
  #     - models:/app/pretrained_models
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_QUEUE=queue:split:4stems

  # worker_5stems:
  #   image: boom-worker
  #   build:
  #     context: ./worker
  #   env_file:
  #     - ./worker/docker.env
  #   volumes:
  #     - tmp:/app/tmp
  #     - models:/app/pretrained_models
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_QUEUE=queue:split:5stems


  # see https://github.com/docker-library/docs/blob/55604f7900451290144c0081e7f622297e519f61/redis/README.md#start-with-persistent-storage
  redis:
    image: redis
    ports:
      - "6379:6379"
