version: "3.4"

services:
  boom:
    image: boom
    build: .
    environment:
      NODE_ENV: production
    env_file:
      - docker.env
    ports:
      - "3000:3000"

  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: ./worker/Dockerfile
    env_file:
      - docker.env

  redis:
    image: redis
    ports:
      - "6379:6379"
