name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          CHANGES=$(git diff-tree --no-commit-id --name-only -r -m $GITHUB_SHA)
          if [[ $CHANGES == *"demo"* || $CHANGES == *"github-pages"* ]]; then echo "ok"; else exit; fi
      - name: Set API url
        run:  |
          sed -i "s/API_BASE_URL/$API_BASE_URL/" demo/index.html
          sed -i 's/BASE_PATH/\/boom/' demo/index.html
          sed -i "s#SENTRY_DSN#$SENTRY_DSN#" demo/index.html
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          SENTRY_DSN: https://bb81525546fe4752a74e871a406791c6@o158732.ingest.sentry.io/5241856

      - name: Delete unecessary files
        run: |
          mkdir gh-pages
          mv ./demo/boom-logo.png ./gh-pages/boom-logo.png
          mv ./demo/index.html ./gh-pages/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          enable_jekyll: true
