name: github pages

on:
  push:
    branches:
      - master
      - 'feat/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: |
      #     CHANGES=$(git diff-tree --no-commit-id --name-only -r -m $GITHUB_SHA)
      #     if [[ $CHANGES == *"demo"* || $CHANGES == *"github-pages"* ]]; then echo "ok"; else exit; fi
      - name: Set API url
        run:  |
          set -e -o pipefail
          DATA="{\"client_id\":\"$TOKEN_CLIENT_ID\",\"client_secret\":\"$TOKEN_CLIENT_SECRET\", \"grant_type\": \"client_credentials\", \"audience\": \"$TOKEN_AUDIENCE\"}"
          API_TOKEN=$(
            curl --request POST \
              --url $TOKEN_ISSUER \
              --header 'content-type: application/json' \
              --data $DATA | jq -r '.access_token'
          )
          sed -i \
            -e "s/API_BASE_URL/$API_BASE_URL/" \
            -e "s/API_TOKEN/$API_TOKEN/" \
            -e "s#BASE_PATH#$BASE_PATH#" \
            -e "s#SENTRY_DSN#$SENTRY_DSN#" \
            demo/index.html
        env:
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          TOKEN_AUDIENCE: ${{ secrets.TOKEN_AUDIENCE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET: ${{ secrets.TOKEN_CLIENT_SECRET }}
          BASE_PATH: /boom
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          SENTRY_DSN: https://bb81525546fe4752a74e871a406791c6@o158732.ingest.sentry.io/5241856

      - name: Delete unecessary files
        run: |
          mkdir gh-pages
          mv ./demo/boom-logo.png ./gh-pages/boom-logo.png
          mv ./demo/index.html ./gh-pages/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          enable_jekyll: true
